info:
  project:
    name: Spring Start
    version: 0.3.1
  # remember to update static/install.sh as well:
  spring-boot:
    version: 1.2.5.RELEASE
endpoints:
  env:
    keysToSanitize: key,secret,password,VCAP_SERVICES

initializr:
  env:
    boms:
      vaadin-bom:
        groupId: com.vaadin
        artifactId: vaadin-bom
        version: 7.5.5
      cloud-bom:
        groupId: org.springframework.cloud
        artifactId: spring-cloud-starter-parent
        mappings:
          - versionRange: "[1.2.3.RELEASE,1.3.0.M1)"
            version: Angel.SR3
          - versionRange: 1.3.0.M5
            version: Brixton.M1
            repositories: spring-snapshots,spring-milestones
  dependencies:
    - name: Core
      content:
        - name: Security
          id: security
          description: Secure your application via spring-security
        - name: AOP
          id: aop
          description: Aspect-oriented programming including spring-aop and AspectJ
        - name: Atomikos (JTA)
          id: jta-atomikos
          description: JTA distributed transactions via Atomikos
          versionRange: 1.2.0.M1
        - name: Bitronix (JTA)
          id: jta-bitronix
          description: JTA distributed transactions via Bitronix
          versionRange: 1.2.0.M1
        - name: Cache
          id: cache
          description: Spring's Cache abstraction
          versionRange: 1.3.0.M1
        - name: DevTools
          id: devtools
          groupId: org.springframework.boot
          artifactId: spring-boot-devtools
          description: Spring Boot Development Tools
          versionRange: 1.3.0.M1
        - name: Lombok
          id: lombok
          groupId: org.projectlombok
          artifactId: lombok
          description: Lombok
          versionRange: 1.3.0.M4 # same as Cloud because the version is defined there
          bom: cloud-bom
    - name: Web
      content:
        - name: Web
          id: web
          description: Full-stack web development with Tomcat and Spring MVC
          facets:
            - web
        - name: Websocket
          id: websocket
          description: Websocket development with SockJS and STOMP
        - name: WS
          id: ws
          description: Contract-first SOAP service development with Spring Web Services
        - name: Jersey (JAX-RS)
          id: jersey
          description: the Jersey RESTful Web Services framework
          versionRange: 1.2.0.RELEASE
        - name: Vaadin
          id: vaadin
          facets:
            - web
          groupId: com.vaadin
          artifactId: vaadin-spring-boot-starter
          version: 1.0.0
          description: Vaadin
          bom: vaadin-bom
        - name: Rest Repositories
          id: data-rest
          description: Exposing Spring Data repositories over REST via spring-data-rest-webmvc
        - name: HATEOAS
          id: hateoas
          description: HATEOAS-based RESTful services
          versionRange: 1.2.2.RELEASE
        - name: Rest Repositories HAL Browser
          id: data-rest-hal
          description: Browsing Spring Data REST repositories with an HTML UI
          groupId: org.springframework.data
          artifactId: spring-data-rest-hal-browser
          versionRange: 1.3.0.M1
        - name: Mobile
          id: mobile
          description: Simplify the development of mobile web applications with spring-mobile
        - name: REST Docs
          id: restdocs
          description: Document RESTful services by combining hand-written and auto-generated documentation
          groupId: org.springframework.restdocs
          artifactId: spring-restdocs-mockmvc
          version: 1.0.0.RC1
          scope: test
    - name: Template Engines
      content:
        - name: Freemarker
          id: freemarker
          description: FreeMarker templating engine
          facets:
            - web
        - name: Velocity
          id: velocity
          description: Velocity templating engine
          facets:
            - web
        - name: Groovy Templates
          id: groovy-templates
          description: Groovy templating engine
          facets:
            - web
        - name: Thymeleaf
          id: thymeleaf
          description: Thymeleaf templating engine, including integration with Spring
          facets:
            - web
        - name: Mustache
          id: mustache
          description: Mustache templating engine
          versionRange: 1.2.2.RELEASE
          facets:
            - web
    - name: Data
      content:
        - name: JDBC
          id: jdbc
          description: JDBC databases
        - name: JPA
          id: data-jpa
          description: Java Persistence API including spring-data-jpa, spring-orm and Hibernate
          aliases:
            - jpa
        - name: MongoDB
          id: data-mongodb
          description: MongoDB NoSQL Database, including spring-data-mongodb
        - name: Redis
          id: redis
          description: REDIS key-value data store, including spring-redis
        - name: Gemfire
          id: data-gemfire
          description: GemFire distributed data store including spring-data-gemfire
        - name: Solr
          id: data-solr
          description: Apache Solr search platform, including spring-data-solr
        - name: Elasticsearch
          id: data-elasticsearch
          description: Elasticsearch search and analytics engine including spring-data-elasticsearch
    - name: Cloud
      bom: cloud-bom
      versionRange: "1.2.3.RELEASE"
      content:
        - name: Cloud Connectors
          id: cloud-connectors
          description: Simplifies connecting to services in cloud platforms, including spring-cloud-connector and spring-cloud-cloudfoundry-connector
          versionRange: 1.2.0.RELEASE
        - name: Cloud Bootstrap
          id: cloud-starter
          description: spring-cloud-context (e.g. Bootstrap context and @RefreshScope)
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter
        - name: Config Client
          id: cloud-config-client
          description: spring-cloud-config Client
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-config
        - name: Config Server
          id: cloud-config-server
          description: Central management for configuration via a git or svn backend
          groupId: org.springframework.cloud
          artifactId: spring-cloud-config-server
        - name: Eureka Discovery
          id: cloud-eureka
          description: Service discovery using spring-cloud-netflix and Eureka
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-eureka
        - name: Eureka Server
          id: cloud-eureka-server
          description: spring-cloud-netflix Eureka Server
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-eureka-server
        - name: AWS
          id: cloud-aws
          description: AWS native services from spring-cloud-aws
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-aws
        - name: Feign
          id: cloud-feign
          description: Declarative REST clients with spring-cloud-netflix Feign
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-feign
        - name: Hystrix
          id: cloud-hystrix
          description: Circuit breaker with spring-cloud-netflix Hystrix
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-hystrix
        - name: Hystrix Dashboard
          id: cloud-hystrix-dashboard
          description: Circuit breaker dashboard with spring-cloud-netflix Hystrix
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-hystrix-dashboard
        - name: OAuth2
          id: cloud-oauth2
          description: OAuth2 and distributed application patterns with spring-cloud-security
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-oauth2
        - name: Ribbon
          id: cloud-ribbon
          description: Client side load balancing with spring-cloud-netflix and Ribbon
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-ribbon
        - name: Turbine
          id: cloud-turbine
          description: Circuit breaker metric aggregation using spring-cloud-netflix with Turbine and server-sent events
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-turbine
        - name: Turbine AMQP
          id: cloud-turbine-amqp
          description: Circuit breaker metric aggregation using spring-cloud-netflix with Turbine and AMQP
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-turbine-amqp
        - name: Zuul
          id: cloud-zuul
          description: Intelligent and programmable routing with spring-cloud-netflix Zuul
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-zuul
        - name: AWS JDBC
          id: cloud-aws-jdbc
          description: Relational databases on AWS with RDS and spring-cloud-aws-jdbc
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-aws-jdbc
        - name: AWS Messaging
          id: cloud-aws-messaging
          description: Messaging on AWS with SQS and spring-cloud-aws-messaging
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-aws-messaging
        - name: Cloud Bus AMQP
          id: cloud-bus-amqp
          description: A simple control bus with AMQP with spring-cloud-bus-amqp
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-bus-amqp
        - name: Cloud Security
          id: cloud-security
          description: Secure load balancing and routing with spring-cloud-security
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-security
        - name: Cloud Foundry Discovery
          id: cloud-cloudfoundry-discovery
          description: Service discovery with Cloud Foundry
          versionRange: 1.3.0.M4
          groupId: org.springframework.cloud
          artifactId: spring-cloud-cloudfoundry-discovery
        - name: Sleuth
          id: cloud-starter-sleuth
          description: Distributed tracing via logs with spring-cloud-sleuth
          versionRange: 1.3.0.M4
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-sleuth
        - name: Zipkin
          id: cloud-starter-zipkin
          description: Distributed tracing via Zipkin and spring-cloud-sleuth-zipkin
          versionRange: 1.3.0.M4
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-zipkin
        - name: Stream Rabbit
          id: cloud-stream-binder-rabbit
          description: Messaging microservices with RabbitMQ 
          versionRange: 1.3.0.M4
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-stream-rabbit
        - name: Stream Redis
          id: cloud-stream-binder-redis
          description: Messaging microservices with Redis
          versionRange: 1.3.0.M4
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-stream-redis
        - name: Stream Kafka
          id: cloud-stream-binder-kafka
          description: Messaging microservices with Kafka
          versionRange: 1.3.0.M4
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-stream-kafka
        - name: Consul Discovery
          id: cloud-starter-consul-discovery
          description: Service discovery with Hashicorp Consul
          versionRange: 1.3.0.M4
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-consul-discovery
        - name: Consul Configuration
          id: cloud-starter-consul-config
          description: Configuration management with Hashicorp Consul
          versionRange: 1.3.0.M4
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-consul-config
        - name: Consul Bus
          id: cloud-starter-consul-bus
          description: Inter instance control events with Hashicorp Consul
          versionRange: 1.3.0.M4
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-consul-bus
        - name: Zookeeper Discovery
          id: cloud-starter-zookeeper-discovery
          description: Service discovery with Zookeeper and spring-cloud-zookeeper-discovery
          versionRange: 1.3.0.M4
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-zookeeper-discovery
        - name: Zookeeper Configuration
          id: cloud-starter-zookeeper-config
          description: Configuration management with Zookeeper and spring-cloud-zookeeper-config
          versionRange: 1.3.0.M4
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-zookeeper-config
        - name: Cluster Redis
          id: cloud-cluster-redis
          description: Leadership election and global state with Redis and spring-cloud-cluster-redis
          versionRange: 1.3.0.M4
          groupId: org.springframework.cloud
          artifactId: spring-cloud-cluster-redis
        - name: Cluster Zookeeper
          id: cloud-cluster-zookeeper
          description: Leadership election and global state with Zookeeper and spring-cloud-cluster-zookeeper
          versionRange: 1.3.0.M4
          groupId: org.springframework.cloud
          artifactId: spring-cloud-cluster-zookeeper
        - name: Cluster Hazelcast
          id: cloud-cluster-hazelcast
          description: Leadership election and global state with Hazelcast and spring-cloud-cluster-hazelcast
          versionRange: 1.3.0.M4
          groupId: org.springframework.cloud
          artifactId: spring-cloud-cluster-hazelcast
    - name: Database
      content:
        - name: H2
          id: h2
          description: H2 database (with embedded support)
          groupId: com.h2database
          artifactId: h2
          scope: runtime
        - name: HSQLDB
          id: hsql
          description: HSQLDB database (with embedded support)
          groupId: org.hsqldb
          artifactId: hsqldb
          scope: runtime
        - name: Apache Derby
          id: derby
          description: Apache Derby database (with embedded support)
          groupId: org.apache.derby
          artifactId: derby
          scope: runtime
          versionRange: 1.2.2.RELEASE
        - name: MySQL
          id: mysql
          description: MySQL jdbc driver
          groupId: mysql
          artifactId: mysql-connector-java
          scope: runtime
        - name: PostgreSQL
          id: postgresql
          description: PostgreSQL jdbc driver
          groupId: org.postgresql
          artifactId: postgresql
          version: 9.4-1201-jdbc41
          scope: runtime
    - name: Social
      content:
        - name: Facebook
          id: social-facebook
          description: spring-social-facebook
        - name: LinkedIn
          id: social-linkedin
          description: spring-social-linkedin
        - name: Twitter
          id: social-twitter
          description: spring-social-twitter
    - name: I/O
      content:
        - name: Batch
          id: batch
          description: Spring Batch including HSQLDB database
        - name: Integration
          id: integration
          description: Common spring-integration modules
        - name: JMS
          id: hornetq
          description: Java Message Service API via HornetQ
        - name: AMQP
          id: amqp
          description: Advanced Message Queuing Protocol via spring-rabbit
        - name: Mail
          id: mail
          description: javax.mail
          versionRange: 1.2.0.RC1
    - name: Ops
      content:
        - name: Actuator
          id: actuator
          description: Production ready features to help you monitor and manage your application
        - name: Actuator Docs
          id: actuator-docs
          description: API documentation for the Actuator endpoints
          versionRange: 1.3.0.M4
          groupId: org.springframework.boot
          artifactId: spring-boot-actuator-docs
        - name: Remote Shell
          id: remote-shell
          description: CRaSH shell integration
  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive
      sts-id: starter.zip
      tags:
        build: maven
        format: project
      default: true
      action: /starter.zip
    - name: Maven POM
      id: maven-build
      description: Generate a Maven pom.xml
      sts-id: pom.xml
      tags:
        build: maven
        format: build
      default: false
      action: /pom.xml
    - name: Gradle Project
      id: gradle-project
      description: Generate a Gradle based project archive
      sts-id: gradle.zip
      tags:
        build: gradle
        format: project
      default: false
      action: /starter.zip
    - name: Gradle Config
      id: gradle-build
      description: Generate a Gradle build file
      sts-id: build.gradle
      tags:
        build: gradle
        format: build
      default: false
      action: /build.gradle
  packagings:
    - name: Jar
      id: jar
      default: true
    - name: War
      id: war
      default: false
  javaVersions:
    - id: 1.8
      default: true
    - id: 1.7
      default: false
    - id: 1.6
      default: false
  languages:
    - name: Java
      id: java
      default: true
    - name: Groovy
      id: groovy
      default: false
  bootVersions:
    - name : Latest SNAPSHOT
      id: 1.2.4.BUILD-SNAPSHOT
      default: false
    - name: 1.2.3
      id: 1.2.3.RELEASE
      default: true
    - name: 1.1.12
      id: 1.1.12.RELEASE
      default: false

