info:
  project:
    name: Spring Start
    version: 0.3.0
# remember to update static/install.sh as well:
  spring-boot:
    version: 1.1.5.RELEASE

initializr:
  dependencies:
    - name: Core
      content:
        - name: Security
          id: security
        - name: AOP
          id: aop
    - name: Data
      content:
        - name: JDBC
          id: jdbc
        - name: JPA
          id: data-jpa
        - name: MongoDB
          id: data-mongodb
        - name: Redis
          id: redis
        - name: Gemfire
          id: data-gemfire
        - name: Solr
          id: data-solr
    - name: I/O
      content:
        - name: Batch
          id: batch
        - name: Integration
          id: integration
        - name: AMQP
          id: amqp
    - name: Web
      content:
        - name: Web
          id: web
        - name: Websocket
          id: websocket
        - name: Rest Repositories
          id: data-rest
        - name: Mobile
          id: mobile
    - name: Template Engines
      content:
        - name: Freemarker
          id: freemarker
        - name: Velocity
          id: velocity
        - name: Groovy Templates
          id: groovy-templates
        - name: Thymeleaf
          id: thymeleaf
    - name: Social
      content:
        - name: Facebook
          id: social-facebook
        - name: LinkedIn
          id: social-linkedin
        - name: Twitter
          id: social-twitter
    - name: Ops
      content:
        - name: Actuator
          id: actuator
        - name: Remote Shell
          id: remote-shell
  types:
    - name: Maven POM
      id: pom.xml
      default: false
      action: /pom.xml
    - name: Maven Project
      id: starter.zip
      default: true
      action: /starter.zip
    - name: Gradle Config
      id: build.gradle
      default: false
      action: /build.gradle
    - name: Gradle Project
      id: gradle.zip
      default: false
      action: /starter.zip
  packagings:
    - name: Jar
      id: jar
      default: true
    - name: War
      id: war
      default: false
  javaVersions:
    - id: 1.6
      default: false
    - id: 1.7
      default: true
    - id: 1.8
      default: false
  languages:
    - name: Groovy
      id: groovy
      default: false
    - name: Java
      id: java
      default: true
  bootVersions:
    - name : Latest SNAPSHOT
      id: 1.2.0.BUILD-SNAPSHOT
      default: false
    - name: 1.1.5
      id: 1.1.5.RELEASE
      default: true
    - name: 1.0.2
      id: 1.0.2.RELEASE
      default: false
