local:
  gcp:
    version: 1.0.0.M3

logging:
  level:
    org.springframework.core.env: warn
    org.springframework.jndi: warn

server:
  compression:
    enabled: true
    mime-types: application/json,text/css,text/html
    min-response-size: 2048

spring:
  jackson:
    serialization:
     write-dates-as-timestamps: false
  resources:
    chain:
      strategy:
        content:
          enabled: true

initializr:
  env:
    boms:
      azure:
        groupId: com.microsoft.azure
        artifactId: azure-spring-boot-bom
        versionProperty: azure.version
        mappings:
          - versionRange: "[1.5.4.RELEASE,2.0.0.RELEASE)"
            version: 0.2.3
          - versionRange: "2.0.0.RELEASE"
            version: 2.0.1
      codecentric-spring-boot-admin:
        groupId: de.codecentric
        artifactId: spring-boot-admin-dependencies
        versionProperty: spring-boot-admin.version
        mappings:
          - versionRange: "[1.5.9.RELEASE,2.0.0.M1)"
            version: 1.5.7
      spring-cloud:
        groupId: org.springframework.cloud
        artifactId: spring-cloud-dependencies
        versionProperty: spring-cloud.version
        order: 50
        mappings:
          - versionRange: "[1.2.3.RELEASE,1.3.0.RELEASE)"
            version: Angel.SR6
          - versionRange: "[1.3.0.RELEASE,1.4.0.RELEASE)"
            version: Brixton.SR7
          - versionRange: "[1.4.0.RELEASE,1.4.x.RELEASE]"
            version: Camden.SR7
          - versionRange: "[1.5.0.RELEASE,1.5.x.RELEASE]"
            version: Edgware.SR3
          - versionRange: "[1.5.x.BUILD-SNAPSHOT,2.0.0.M1)"
            version: Edgware.BUILD-SNAPSHOT
            repositories: spring-snapshots,spring-milestones
          - versionRange: "[2.0.0.M3, 2.0.0.M5)"
            version: Finchley.M2
            repositories: spring-milestones
          - versionRange: "[2.0.0.M5, 2.0.0.M5]"
            version: Finchley.M3
            repositories: spring-milestones
          - versionRange: "[2.0.0.M6, 2.0.0.M6]"
            version: Finchley.M4
            repositories: spring-milestones
          - versionRange: "[2.0.0.M7, 2.0.0.M7]"
            version: Finchley.M5
            repositories: spring-milestones
          - versionRange: "[2.0.0.RC1, 2.0.0.RC1]"
            version: Finchley.M6
            repositories: spring-milestones
          - versionRange: "[2.0.0.RC2,2.0.0.RC2]"
            version: Finchley.M7
            repositories: spring-milestones
          - versionRange: "[2.0.0.RELEASE,2.0.0.RELEASE]"
            version: Finchley.M9
            repositories: spring-milestones
          - versionRange: "[2.0.1.RELEASE,2.0.x.RELEASE]"
            version: Finchley.RC1
            repositories: spring-milestones
          - versionRange: "2.0.x.BUILD-SNAPSHOT"
            version: Finchley.BUILD-SNAPSHOT
            repositories: spring-snapshots,spring-milestones
      spring-cloud-gcp:
        groupId: org.springframework.cloud
        artifactId: spring-cloud-gcp-dependencies
        versionProperty: spring-cloud-gcp.version
        additionalBoms: [spring-cloud]
        version: ${local.gcp.version}
        repositories: spring-milestones
      spring-cloud-services:
        groupId: io.pivotal.spring.cloud
        artifactId: spring-cloud-services-dependencies
        versionProperty: spring-cloud-services.version
        additionalBoms: [spring-cloud]
        mappings:
          - versionRange: "[1.3.0.RELEASE,1.4.0.RELEASE)"
            version: 1.2.1.RELEASE
          - versionRange: "[1.4.0.RELEASE,1.4.x.RELEASE]"
            version: 1.5.0.RELEASE
          - versionRange: "[1.5.0.RELEASE,1.5.x.BUILD-SNAPSHOT]"
            version: 1.6.3.RELEASE
          - versionRange: "[2.0.0.RELEASE,2.0.x.RELEASE]"
            version: 2.0.0.M1
            repositories: spring-milestones
          - versionRange: "2.0.x.BUILD-SNAPSHOT"
            version: 2.0.0.BUILD-SNAPSHOT
            repositories: spring-snapshots,spring-milestones
      spring-cloud-task:
        groupId: org.springframework.cloud
        artifactId: spring-cloud-task-dependencies
        versionProperty: spring-cloud-task.version
        order: 30
        mappings:
          - versionRange: "[1.3.0.RELEASE, 1.4.0.RELEASE]"
            version: 1.0.3.RELEASE
          - versionRange: "[1.4.0.RELEASE, 1.5.0.RC1)"
            version: 1.1.2.RELEASE
          - versionRange: "[1.5.0.RC1, 2.0.0.M1)"
            version: 1.2.2.RELEASE
          - versionRange: "[2.0.0.M2, 2.0.0.RELEASE)"
            version: 2.0.0.M3
            repositories: spring-milestones
          - versionRange: "[2.0.0.RELEASE,2.0.x.RELEASE]"
            version: 2.0.0.RC1
            repositories: spring-milestones
          - versionRange: "2.0.x.BUILD-SNAPSHOT"
            version: 2.0.0.BUILD-SNAPSHOT
            repositories: spring-snapshots,spring-milestones
      spring-statemachine:
        groupId: org.springframework.statemachine
        artifactId: spring-statemachine-bom
        versionProperty: spring-statemachine.version
        mappings:
          - versionRange: "[2.0.0.RC1,2.0.0.RC1]"
            version: 2.0.0.M4
            repositories: spring-milestones
          - versionRange: "[2.0.0.RC2,2.0.0.RC2]"
            version: 2.0.0.M5
            repositories: spring-milestones
          - versionRange: "2.0.0.RELEASE"
            version: 2.0.1.RELEASE
      vaadin:
        groupId: com.vaadin
        artifactId: vaadin-bom
        versionProperty: vaadin.version
        mappings:
          - versionRange: "[1.3.0.RELEASE, 1.5.0.M1)"
            version: 7.7.7
          - versionRange: "1.5.0.M1"
            version: 8.3.1
      keycloak:
        groupId: org.keycloak.bom
        artifactId: keycloak-adapter-bom
        versionProperty: keycloak.version
        version: 3.4.2.Final
    gradle:
      dependency-management-plugin-version: 0.6.0.RELEASE
    kotlin:
      default-version: 1.2.20
  dependencies:
    - name: Infrastructure Spring Cloud Modules
      bom: spring-cloud
      content:
        - name: Spring Cloud Config Server
          id: cloud-config-server
          groupId: org.springframework.cloud
          artifactId: spring-cloud-config-server
          description: Central management for configuration via a git or svn backend
          versionRange: 1.2.3.RELEASE
          links:
            - rel: guide
              href: https://spring.io/guides/gs/centralized-configuration/
              description: Centralized Configuration
        - name: Spring Cloud Gateway
          id: cloud-gateway
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-gateway
          description: Intelligent and programmable routing with the reactive Spring Cloud Gateway
          links:
            - rel: guide
              href: https://github.com/spring-cloud-samples/spring-cloud-gateway-sample
              description: Using Spring Cloud Gateway
        - name: Spring Cloud Eureka Server
          id: cloud-eureka-server
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-netflix-eureka-server
          description: Spring Cloud Service Registry and Discovery
          links:
            - rel: guide
              href: https://spring.io/guides/gs/service-registration-and-discovery/
              description: Service Registration and Discovery
        - name: Spring Cloud Hystrix Dashboard
          id: cloud-hystrix-dashboard
          description: Circuit breaker dashboard with spring-cloud-netflix Hystrix
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-netflix-hystrix-dashboard
          links:
            - rel: guide
              href: https://cloud.spring.io/spring-cloud-netflix/single/spring-cloud-netflix.html#_circuit_breaker_hystrix_dashboard
              description: Circuit Breaker Hystrix Dashboard
    - name: Azure Spring Cloud Modules
      bom: azure
      content:
        - name: Azure Service Bus
          id: azure-service-bus
          description: Azure Service Bus
          groupId: com.microsoft.azure
          artifactId: azure-servicebus-spring-boot-starter
          links:
            - rel: guide
              href: https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-servicebus-spring-boot-sample
              description: Sample project for Azure Spring Service Bus
  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive
      sts-id: starter.zip
      tags:
        build: maven
        format: project
      default: true
      action: /starter.zip
    - name: Maven POM
      id: maven-build
      description: Generate a Maven pom.xml
      sts-id: pom.xml
      tags:
        build: maven
        format: build
      default: false
      action: /pom.xml
    - name: Gradle Project
      id: gradle-project
      description: Generate a Gradle based project archive
      sts-id: gradle.zip
      tags:
        build: gradle
        format: project
      default: false
      action: /starter.zip
    - name: Gradle Config
      id: gradle-build
      description: Generate a Gradle build file
      sts-id: build.gradle
      tags:
        build: gradle
        format: build
      default: false
      action: /build.gradle
  packagings:
    - name: Jar
      id: jar
      default: true
    - name: War
      id: war
      default: false
  javaVersions:
    - id: 10
      default: false
    - id: 9
      default: false
    - id: 1.8
      name: 8
      default: true
    - id: 1.7
      name: 7
      default: false
  languages:
    - name: Java
      id: java
      default: true
    - name: Kotlin
      id: kotlin
      default: false
    - name: Groovy
      id: groovy
      default: false
  bootVersions:
    - name : Latest SNAPSHOT
      id: 1.2.4.BUILD-SNAPSHOT
      default: false
    - name: 1.2.3
      id: 1.2.3.RELEASE
      default: true
    - name: 1.1.12
      id: 1.1.12.RELEASE
      default: false
