info:
  project:
    name: Spring Start
    version: 0.2.0
# remember to update static/install.sh as well:
  spring-boot:
    version: 1.1.3.RELEASE

projects:
  styles:
    - name: Web
      value: web
    - name: Websocket
      value: websocket
    - name: Freemarker
      value: freemarker
    - name: Velocity
      value: velocity
    - name: Groovy Templates
      value: groovy-templates
    - name: Thymeleaf
      value: thymeleaf
    - name: Actuator
      value: actuator
    - name: Security
      value: security
    - name: Batch
      value: batch
    - name: JDBC
      value: jdbc
    - name: Integration
      value: integration
    - name: AMQP
      value: amqp
    - name: AOP
      value: aop
    - name: JPA
      value: data-jpa
    - name: MongoDB
      value: data-mongodb
    - name: Redis
      value: redis
    - name: Gemfire
      value: data-gemfire
    - name: Solr
      value: data-solr
    - name: Rest Repositories
      value: data-rest
    - name: Remote Shell
      value: remote-shell
    - name: Mobile
      value: mobile
    - name: Facebook
      value: social-facebook
    - name: LinkedIn
      value: social-linkedin
    - name: Twitter
      value: social-twitter
  types:
    - name: Maven POM
      action: /pom.xml
      value: pom.xml
      selected: false
    - name: Maven Project
      action: /starter.zip
      value: starter.zip
      selected: true
    - name: Gradle Config
      action: /build.gradle
      value: build.gradle
      selected: false
    - name: Gradle Project
      action: /starter.zip
      value: gradle.zip
      selected: false
  packagings:
    - name: Jar
      value: jar
      selected: true
    - name: War
      value: war
      selected: false
  javaVersions:
    - value: 1.6
      selected: false
    - value: 1.7
      selected: true
    - value: 1.8
      selected: false
  languages:
    - name: Groovy
      value: groovy
      selected: false
    - name: Java
      value: java
      selected: true
  bootVersions:
    - value: 1.1.4.BUILD-SNAPSHOT
      selected: false
    - value: 1.1.3.RELEASE
      selected: true
    - value: 1.0.2.RELEASE
      selected: false
