info:
  project:
    name: Spring Start
    version: 0.2.1
# remember to update static/install.sh as well:
  spring-boot:
    version: 1.1.5.RELEASE

projects:
  styles:
    - name: Core
      starters:
        - name: Security
          value: security
        - name: AOP
          value: aop
    - name: Data
      starters:
        - name: JDBC
          value: jdbc
        - name: JPA
          value: data-jpa
        - name: MongoDB
          value: data-mongodb
        - name: Redis
          value: redis
        - name: Gemfire
          value: data-gemfire
        - name: Solr
          value: data-solr
    - name: I/O
      starters:
      - name: Batch
        value: batch
      - name: Integration
        value: integration
      - name: AMQP
        value: amqp
    - name: Web
      starters:
        - name: Web
          value: web
        - name: Websocket
          value: websocket
        - name: Rest Repositories
          value: data-rest
        - name: Mobile
          value: mobile
    - name: Template Engines
      starters:
        - name: Freemarker
          value: freemarker
        - name: Velocity
          value: velocity
        - name: Groovy Templates
          value: groovy-templates
        - name: Thymeleaf
          value: thymeleaf
    - name: Social
      starters:
        - name: Facebook
          value: social-facebook
        - name: LinkedIn
          value: social-linkedin
        - name: Twitter
          value: social-twitter
    - name: Ops
      starters:
        - name: Actuator
          value: actuator
        - name: Remote Shell
          value: remote-shell
  types:
    - name: Maven POM
      action: /pom.xml
      value: pom.xml
      selected: false
    - name: Maven Project
      action: /starter.zip
      value: starter.zip
      selected: true
    - name: Gradle Config
      action: /build.gradle
      value: build.gradle
      selected: false
    - name: Gradle Project
      action: /starter.zip
      value: gradle.zip
      selected: false
  packagings:
    - name: Jar
      value: jar
      selected: true
    - name: War
      value: war
      selected: false
  javaVersions:
    - value: 1.6
      selected: false
    - value: 1.7
      selected: true
    - value: 1.8
      selected: false
  languages:
    - name: Groovy
      value: groovy
      selected: false
    - name: Java
      value: java
      selected: true
  bootVersions:
    - value: 1.2.0.BUILD-SNAPSHOT
      selected: false
    - value: 1.1.5.RELEASE
      selected: true
    - value: 1.0.2.RELEASE
      selected: false
